---

server:
  port: 4000

spring:
  devtools:
    restart:
      additional-paths:
        - src/main/resources/static
        - src/main/resources/templates
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths:
              - /**
      cache:
        cachecontrol:
          max-age: 31536000
          must-revalidate: true

okta:
  oauth2:
    issuer: soni.uk.auth0.com
    client-id: blRQtZDn4bi8qCDJlxFUm83filLOJYHo
    client-secret: JTUXmEOPLNbb_D0rx3et4JucuFM0lCJvYL6UdSY2SlYDn83_4KgaBxOctsZVYK0s

...
